/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management;

import java.sql.*;
import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author AAYUSH_RANA
 */
public class searchp extends javax.swing.JFrame {

    /**
     * Creates new form searchp
     */
    String name_="";
    String mobile_="";
    String id_="";
    String age_="";
    String city_="";
    String disease_="";
    Connection con =null;
    public searchp() {
        initComponents();
        con = dbcon.getCon();
        System.out.println("Search drivers registered!!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_result = new javax.swing.JList();
        searchp_delete = new javax.swing.JButton();
        searchp_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        l_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Search Records");

        l_name.setText("Name");

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        tf_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nameKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(list_result);

        searchp_delete.setText("Delete");
        searchp_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchp_deleteActionPerformed(evt);
            }
        });

        searchp_update.setText("Update");
        searchp_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchp_updateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel2.setText("Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(searchp_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchp_update)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_name)
                        .addGap(29, 29, 29)
                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_name)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchp_delete)
                    .addComponent(searchp_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_status, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        //
    }//GEN-LAST:event_tf_nameActionPerformed

    private void searchp_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchp_deleteActionPerformed
         try{           
         Statement s=con.createStatement();
         String s_i=list_result.getSelectedValue().toString();
        String idary[]=s_i.split("-");
        String q="DELETE FROM `patient`WHERE Id="+idary[2]+"";             
	//System.out.println(q);
	s.executeUpdate(q);
        l_status.setText("-: Record Successfully Deleted :-");
         }
         catch(Exception e)
         {
             l_status.setText(e.toString());
         }
    }//GEN-LAST:event_searchp_deleteActionPerformed
    
    private void searchp_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchp_updateActionPerformed
    
        String s_i=list_result.getSelectedValue().toString();
        String idary[]=s_i.split("-");
        //System.out.print(idary[2]);
        updatep u = new updatep(idary[2]);
        u.setVisible(true);
    }//GEN-LAST:event_searchp_updateActionPerformed

    private void tf_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nameKeyReleased
         String pname = tf_name.getText();
          try{
        Statement s=con.createStatement();
        String q="SELECT id,Name, Mobile FROM `patient`WHERE Name LIKE '%"+pname+"%'";             
	//System.out.println(q);
	s.executeQuery(q);
        ResultSet rs = s.getResultSet();
        Vector list_ = new Vector();
        while (rs.next()) {
            id_= rs.getString(1);
            name_ = rs.getString(2);
            mobile_ = rs.getString(3);
            
            String data = name_ + " - " + mobile_+"-"+id_;
            list_.addElement(data);
            
        }
       //list_.addElement("He");
         list_result.setListData(list_);
        
        l_status.setText("-: Records Sussessfully Displayed :-");
        }
        catch(Exception e)
        {
            l_status.setText(e.toString());
            //System.out.println(e);
        }
    }//GEN-LAST:event_tf_nameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_status;
    private javax.swing.JList list_result;
    private javax.swing.JButton searchp_delete;
    private javax.swing.JButton searchp_update;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
